[functions.account-maintenance]
verify_jwt = false

[functions.analytics-traffic]
verify_jwt = false

[functions.service-execution-scheduler-run]
verify_jwt = false

[functions.report-subscription-delivery-run]
verify_jwt = false
