import {test,expect} from '@playwright/test';
import fs from 'node:fs';import path from 'node:path';
const source=fs.readFileSync(path.join(process.cwd(),'js/admin-owner-management-command-ui.js'),'utf8');
const now=()=>new Date().toISOString();
const meta=()=>({state:'current',confidence:'high',last_authoritative_update:now(),reason:'Required communication sources are current.'});
function fixture(){return{
  ok:true,source_visibility:{jobs:true,finance:true,safety:false,admin:false},source_freshness:{},
  management_metric_confidence:{communication_readiness:meta(),stock_readiness:{state:'missing',confidence:'low'},utilization_support:{state:'unavailable',confidence:'unavailable'},estimate_to_cash:{state:'unavailable',confidence:'unavailable'},recurring_retention:{state:'missing',confidence:'low'},route_efficiency:{state:'missing',confidence:'low'},capacity_forecast:{state:'missing',confidence:'low'},crews_today:meta(),completion_today:meta(),schedule_risk:meta(),revenue:meta(),gross_margin:meta(),receivables:meta(),cash_bank:meta(),recurring_completion:meta(),winter_operations:meta(),fall_cleanup:meta(),equipment_blockers:meta(),workforce_blockers:{state:'unavailable',confidence:'unavailable'},finance_readiness:meta()},
  four_season_capacity_forecast:null,route_crew_efficiency_evidence:null,recurring_renewal_retention_workbench:null,estimate_to_cash_leakage_workbench:null,labour_equipment_fleet_utilization_support:null,materials_consumables_seasonal_stock_readiness:null,
  customer_communication_readiness_queue:{
    source_queries_ok:true,horizon_end:'2026-10-14',
    summary:{queue_count:6,weather_workability_changes:1,reschedule_notices:1,eta_changes:1,completion_followups:1,recurring_service_notices:1,overdue_customer_followups:1,invoice_reminder_candidates:1,delivery_attention_count:1,merged_multi_source_count:1},
    readiness_queue:[
      {dedupe_key:'schedule:wo-359',signal_type:'weather_workability_change',signal_types:['weather_workability_change','eta_change'],client_name:'Maple Property',site_name:'North Site',work_order_number:'WO-359',service_context:'fall_cleanup',scheduled_at:'2026-10-01T14:00:00Z',reason:'Rain delay',preferred_contact_method:'email',preferred_contact_window:'morning',detail:'Recorded workability decision reschedule · Dispatch start changed.',source_link_count:3,navigation_target:'operations'},
      {dedupe_key:'completion:wo-360',signal_type:'completion_followup',signal_types:['completion_followup'],client_name:'Pine Client',work_order_number:'WO-360',service_context:'completed_work',scheduled_at:'2026-09-29T18:00:00Z',reason:'completion follow-up has no later outbound CRM interaction',detail:'Approved/completed closeout has no later outbound CRM interaction recorded.',source_link_count:1,navigation_target:'jobs'},
      {dedupe_key:'recurring:RSA-359:2026-10-03',signal_type:'recurring_service_notice',signal_types:['recurring_service_notice'],client_name:'Oak Customer',service_context:'Weekly Mowing',scheduled_at:'2026-10-03',reason:'upcoming recurring service visit',detail:'Upcoming recurring visit is in the 14-day operating window.',source_link_count:1,navigation_target:'jobs'},
      {dedupe_key:'crm_followup:fu-359',signal_type:'overdue_customer_followup',signal_types:['overdue_customer_followup'],client_name:'Elm Customer',service_context:'complaint',scheduled_at:'2026-09-28T12:00:00Z',reason:'Call customer back',detail:'CRM follow-up is overdue and remains pending.',source_link_count:1,navigation_target:'jobs'},
      {dedupe_key:'invoice:inv-359',signal_type:'invoice_reminder_candidate',signal_types:['invoice_reminder_candidate'],client_name:'Birch Customer',service_context:'accounts_receivable',scheduled_at:'2026-09-20',reason:'invoice is 10 day(s) past due',detail:'Invoice INV-359 has recorded balance due 425.00.',source_link_count:1,navigation_target:'finance'}
    ],
    delivery_attention:[{outbox_id:'out-359',delivery_status:'manual_review',work_order_number:'WO-361',client_name:'Spruce Customer',live_update_title:'Crew delayed',attempt_count:1,detail:'Existing protected customer-notification delivery requires operational review.'}],
    duplicate_boundary:'Queue identity is deterministic. Workability and dispatch schedule-change evidence collapse to one work-order communication candidate while retaining every source link.',
    context_boundary:'Message context is assembled from source references, service/timing/reason, and CRM preferred contact method/window only. Customer email addresses, phone numbers and portal tokens are not returned by this management queue.',
    completion_boundary:'A completion follow-up is suppressed when an outbound CRM interaction linked to the same work order is recorded at or after the closeout approval/signoff evidence.',
    recurring_boundary:'Recurring-service notices are readiness candidates only. The recurring occurrence key is retained for duplicate suppression; no message is sent and no customer preference is inferred.',
    finance_boundary:'Invoice-reminder candidates appear only with Finance visibility and are based on recorded positive balance plus days-past-due evidence. This layer cannot send reminders, collect payment or mutate A/R.',
    delivery_boundary:'Existing notification outbox state is review evidence only. Protected consent, enqueue, claim, retry and provider delivery remain the existing customer-notification authority.',
    authority_boundary:'Read-only readiness and queue-quality evidence. This scope does not send email/text, publish live updates, reschedule work, change workability decisions, create CRM interactions/follow-ups, retry delivery, mutate invoices or contact a provider.'
  },
  owner_jobs:[],owner_dispatch:[],owner_production:[],owner_profitability:[],owner_timekeeping_summary:[],owner_recurring:[],owner_recurring_visits:[],owner_crews:[],owner_storms:[],owner_storm_routes:[],owner_seasonal_work:[],owner_safety:[],owner_equipment:[],owner_maintenance:[],owner_training_summary:[],owner_workforce_summary:[],owner_receivables:[],owner_bank:[],owner_finance_exceptions:[],owner_close_dashboard:[],owner_workability:[],owner_equipment_use:[],owner_fleet:[],owner_material_stock:[],owner_material_plans:[],owner_crm_followups:[],owner_notification_delivery:[],owner_closeouts:[]
}}
async function boot(page,data=fixture()){await page.setViewportSize({width:390,height:844});await page.setContent('<!doctype html><html><body><section id="admin"></section></body></html>');await page.evaluate(payload=>{window.YWIRouter={showSection:s=>window.__route=s};window.YWIAdminHub={open:s=>window.__group=s};window.YWIAPI={loadAdminDirectory:async()=>payload}},data);await page.addScriptTag({content:source});await page.evaluate(()=>window.YWIOwnerManagementCommandUI.mount({api:window.YWIAPI}));await expect(page.locator('#owner359Communications')).toBeVisible();}
test('Build 359 renders deduplicated communication readiness without contact secrets or sending',async({page})=>{await boot(page);const h=page.locator('#owner359Communications');await expect(h).toContainText('Ready for review');await expect(h).toContainText('WEATHER WORKABILITY CHANGE + ETA CHANGE');await expect(h).toContainText('Sources: 3 · key schedule:wo-359');await expect(h).toContainText('Completion follow-up');await expect(h).toContainText('RSA-359');await expect(h).toContainText('INV-359');await expect(h).toContainText('MANUAL REVIEW · WO-361');await expect(h).toContainText('Customer email addresses, phone numbers and portal tokens are not returned');await expect(page.locator('.owner359-communications')).toContainText('Review only — no send');await expect(h).not.toContainText('customer@example.com');await expect(h).not.toContainText('555-0100');await expect(h).not.toContainText('portal-secret-359');expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBeFalsy();});
test('Build 359 withholds queue facts when canonical reads fail',async({page})=>{const d=fixture();d.customer_communication_readiness_queue.source_queries_ok=false;await boot(page,d);await expect(page.locator('#owner359Communications')).toContainText('source queries failed');await expect(page.locator('#owner359Communications')).not.toContainText('WO-359');});
test('Build 359 keeps invoice reminders Finance-scoped',async({page})=>{const d=fixture();d.source_visibility.finance=false;d.customer_communication_readiness_queue.readiness_queue=d.customer_communication_readiness_queue.readiness_queue.filter(r=>r.signal_type!=='invoice_reminder_candidate');await boot(page,d);await expect(page.locator('#owner359Communications')).toContainText('Invoice reminders');await expect(page.locator('#owner359Communications')).toContainText('Unavailable');await expect(page.locator('#owner359Communications')).not.toContainText('INV-359');});
test('Build 359 navigation stays deliberate',async({page})=>{await boot(page);await page.locator('.owner359-communications button').filter({hasText:'Open source workspace'}).first().click();await page.waitForTimeout(10);expect(await page.evaluate(()=>window.__route)).toBe('admin');expect(await page.evaluate(()=>window.__group)).toBe('operations');});
