import {test,expect} from '@playwright/test';
import fs from 'node:fs';import path from 'node:path';
const source=fs.readFileSync(path.join(process.cwd(),'js/admin-owner-management-command-ui.js'),'utf8');
const now=()=>new Date().toISOString();
const meta=()=>({state:'current',confidence:'high',last_authoritative_update:now(),reason:'Required data-quality sources are current.'});
function fixture(){return{
  ok:true,source_visibility:{jobs:true,finance:false,safety:false,admin:true},source_freshness:{},
  management_metric_confidence:{
    data_quality_reconciliation:meta(),communication_readiness:{state:'missing',confidence:'low'},stock_readiness:{state:'missing',confidence:'low'},
    utilization_support:{state:'missing',confidence:'low'},estimate_to_cash:{state:'unavailable',confidence:'unavailable'},recurring_retention:{state:'missing',confidence:'low'},
    route_efficiency:{state:'missing',confidence:'low'},capacity_forecast:{state:'missing',confidence:'low'},crews_today:meta(),completion_today:meta(),schedule_risk:meta(),
    revenue:{state:'unavailable',confidence:'unavailable'},gross_margin:{state:'unavailable',confidence:'unavailable'},receivables:{state:'unavailable',confidence:'unavailable'},
    cash_bank:{state:'unavailable',confidence:'unavailable'},labour_utilization:meta(),recurring_completion:meta(),winter_operations:meta(),fall_cleanup:meta(),
    safety_blockers:{state:'unavailable',confidence:'unavailable'},equipment_blockers:meta(),workforce_blockers:meta(),finance_readiness:{state:'unavailable',confidence:'unavailable'}
  },
  four_season_capacity_forecast:null,route_crew_efficiency_evidence:null,recurring_renewal_retention_workbench:null,estimate_to_cash_leakage_workbench:null,
  labour_equipment_fleet_utilization_support:null,materials_consumables_seasonal_stock_readiness:null,customer_communication_readiness_queue:null,
  data_quality_duplicate_orphan_reconciliation:{
    source_queries_ok:true,reference_coverage_complete:true,
    summary:{total_signals:6,duplicate_customer_candidates:1,duplicate_property_candidates:1,broken_canonical_references:1,cross_module_link_mismatches:1,stale_assignments:1,conflicting_season_service_tags:1},
    reconciliation_queue:[
      {signal_type:'broken_canonical_reference',severity:'high_review',entity_type:'recurring_service',entity_id:'rsa-360',reference:'RSA-360',title:'Recurring service references an unavailable route',detail:'Agreement RSA-360 records route id route-missing but that id is absent from the complete loaded canonical route source.',match_basis:[],related_entities:[{type:'recurring_service',id:'rsa-360',reference:'RSA-360'},{type:'route',id:'route-missing'}],source_links:[{source_type:'recurring_service',source_id:'rsa-360',reference:'RSA-360'}],suggested_action:'Open the recurring-service program and the referenced source. Repair the link deliberately; do not synthesize a replacement record.',navigation_target:'operations'},
      {signal_type:'cross_module_link_mismatch',severity:'high_review',entity_type:'job',entity_id:'job-360',reference:'JOB-360',title:'Job customer/property ownership mismatch',detail:'The active job customer id differs from the customer that owns its canonical property.',match_basis:[],related_entities:[{type:'job',id:'job-360',reference:'JOB-360'},{type:'customer',id:'cust-a'},{type:'property',id:'prop-b',client_id:'cust-b'}],source_links:[{source_type:'job',source_id:'job-360',reference:'JOB-360'}],suggested_action:'Review Jobs and CRM together and correct the canonical ownership link without replacing or deleting source history.',navigation_target:'jobs'},
      {signal_type:'stale_assignment',severity:'high_review',entity_type:'dispatch',entity_id:'disp-360',reference:'WO-360',title:'Active dispatch includes unavailable equipment',detail:'Assigned equipment EQ-360 is locked out, retired/inactive, or on replacement hold.',match_basis:[],related_entities:[{type:'dispatch',id:'disp-360'},{type:'equipment',id:'eq-360',reference:'EQ-360'}],source_links:[{source_type:'dispatch',source_id:'disp-360',reference:'WO-360'}],suggested_action:'Open Dispatch and Equipment Registry. Preserve the lockout/retirement authority and reassign equipment deliberately if required.',navigation_target:'jobs'},
      {signal_type:'conflicting_season_service_tag',severity:'review',entity_type:'material_plan',entity_id:'mat-360',reference:'EST-360',title:'Season/service tags conflict',detail:'Recorded service context "snow clearing" maps to winter while the source records season_context "fall".',match_basis:[],related_entities:[{type:'material_plan',id:'mat-360',reference:'EST-360'}],source_links:[{source_type:'material_plan',source_id:'mat-360',reference:'EST-360'}],suggested_action:'Open the source record and confirm whether the service label or season tag is wrong.',navigation_target:'jobs'},
      {signal_type:'duplicate_customer_candidate',severity:'high_review',entity_type:'customer_pair',entity_id:'cust-a|cust-b',reference:'CUST-A ↔ CUST-B',title:'Maple Holdings ↔ Maple Holdings Ltd',detail:'Two active canonical customer records share same email, same normalized name and postal. Contact values are used only for matching and are not returned in this workbench.',match_basis:['same_email','same_normalized_name_and_postal'],related_entities:[{type:'customer',id:'cust-a',reference:'CUST-A',name:'Maple Holdings'},{type:'customer',id:'cust-b',reference:'CUST-B',name:'Maple Holdings Ltd'}],source_links:[{source_type:'crm_customer',source_id:'cust-a',reference:'CUST-A'},{source_type:'crm_customer',source_id:'cust-b',reference:'CUST-B'}],suggested_action:'Open CRM, compare service/property/history evidence, and decide manually whether records represent the same customer. Preserve both source IDs and audit history until an explicit reconciliation workflow exists.',navigation_target:'crm'},
      {signal_type:'duplicate_property_candidate',severity:'review',entity_type:'property_pair',entity_id:'prop-a|prop-b',reference:'PROP-A ↔ PROP-B',title:'North Yard ↔ North Yard duplicate',detail:'Two active property records share same normalized service address. Address/coordinate values are used for matching; source property IDs remain distinct.',match_basis:['same_normalized_service_address'],related_entities:[{type:'property',id:'prop-a',reference:'PROP-A',name:'North Yard'},{type:'property',id:'prop-b',reference:'PROP-B',name:'North Yard duplicate'}],source_links:[{source_type:'crm_property',source_id:'prop-a',reference:'PROP-A'},{source_type:'crm_property',source_id:'prop-b',reference:'PROP-B'}],suggested_action:'Open Property / CRM, compare ownership, service history, zones and access data. Do not merge or delete automatically; preserve both property identities until reviewed.',navigation_target:'crm'}
    ],
    duplicate_customer_pairs:[],duplicate_property_pairs:[],reference_and_assignment_issues:[],season_tag_conflicts:[],
    duplicate_boundary:'Duplicate signals are candidates, not identity decisions. Customer matching uses exact normalized email/phone or normalized name plus postal evidence; property matching uses normalized service address/postal or rounded coordinates. Contact values are never returned by this workbench.',
    reference_boundary:'Broken-reference checks are emitted only when all required canonical reference sources are successfully loaded below their configured row caps. If coverage is partial, reference-gap findings are withheld rather than treating missing rows as missing business records.',
    assignment_boundary:'Stale crew/equipment signals describe recorded assignment inconsistencies only. They do not infer employee performance and cannot clear equipment lockouts or reassign crews/equipment.',
    season_boundary:'Season/service conflicts use the existing four-season Ontario taxonomy as a review heuristic: spring/summer landscaping and lawn work, fall cleanup/leaf work, and winter snow/ice service. Four-season/other tags are not treated as conflicts.',
    destructive_boundary:'This workbench cannot merge or delete customers/properties, delete history, rewrite foreign keys, reassign crews/equipment, clear lockouts, or mutate Jobs/CRM/Finance/Safety records. Every correction remains a deliberate action in the canonical source workflow.',
    audit_boundary:'Source IDs and references are retained on every reconciliation candidate so audit and historical identity remain visible during review.',
    authority_boundary:'Read-only data-quality evidence assembled from canonical CRM, Jobs, Dispatch, Recurring Service, Crew, Equipment, Route, Workability and Material Estimator sources.'
  },
  owner_jobs:[],owner_dispatch:[],owner_production:[],owner_profitability:[],owner_timekeeping_summary:[],owner_recurring:[],owner_recurring_visits:[],owner_crews:[],
  owner_storms:[],owner_storm_routes:[],owner_seasonal_work:[],owner_safety:[],owner_equipment:[],owner_maintenance:[],owner_training_summary:[],owner_workforce_summary:[],
  owner_receivables:[],owner_bank:[],owner_finance_exceptions:[],owner_close_dashboard:[],owner_workability:[],owner_equipment_use:[],owner_fleet:[],owner_material_stock:[],
  owner_material_plans:[],owner_crm_followups:[],owner_notification_delivery:[],owner_closeouts:[],owner_crm_properties:[]
}}
async function boot(page,data=fixture()){await page.setViewportSize({width:390,height:844});await page.setContent('<!doctype html><html><body><section id="admin"></section></body></html>');await page.evaluate(payload=>{window.YWIRouter={showSection:s=>window.__route=s};window.YWIAdminHub={open:s=>window.__group=s};window.YWIAPI={loadAdminDirectory:async()=>payload}},data);await page.addScriptTag({content:source});await page.evaluate(()=>window.YWIOwnerManagementCommandUI.mount({api:window.YWIAPI}));await expect(page.locator('#owner360DataQuality')).toBeVisible();}
test('Build 360 renders evidence-backed reconciliation without destructive controls or contact secrets',async({page})=>{await boot(page);const h=page.locator('#owner360DataQuality');await expect(h).toContainText('Signals');await expect(h).toContainText('DUPLICATE CUSTOMER CANDIDATE');await expect(h).toContainText('CUST-A ↔ CUST-B');await expect(h).toContainText('BROKEN CANONICAL REFERENCE');await expect(h).toContainText('JOB-360');await expect(h).toContainText('EQ-360');await expect(h).toContainText('winter');await expect(page.locator('.owner360-data-quality')).toContainText('No destructive auto-fix');await expect(h).toContainText('cannot merge or delete customers/properties');await expect(h).not.toContainText('maple@example.com');await expect(h).not.toContainText('5195550100');await expect(h).not.toContainText('portal-secret');await expect(page.locator('button')).not.toContainText(/merge|delete/i);expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBeFalsy();});
test('Build 360 withholds reference-gap facts when canonical coverage is capped',async({page})=>{const d=fixture();d.data_quality_duplicate_orphan_reconciliation.reference_coverage_complete=false;d.data_quality_duplicate_orphan_reconciliation.reconciliation_queue=d.data_quality_duplicate_orphan_reconciliation.reconciliation_queue.filter(r=>!['broken_canonical_reference','cross_module_link_mismatch','stale_assignment'].includes(r.signal_type));await boot(page,d);const h=page.locator('#owner360DataQuality');await expect(h).toContainText('Reference-gap findings withheld');await expect(h).toContainText('Withheld');await expect(h).not.toContainText('RSA-360');});
test('Build 360 withholds all counts when a canonical source query fails',async({page})=>{const d=fixture();d.data_quality_duplicate_orphan_reconciliation.source_queries_ok=false;await boot(page,d);await expect(page.locator('#owner360DataQuality')).toContainText('source queries failed');await expect(page.locator('#owner360DataQuality')).not.toContainText('CUST-A');});
test('Build 360 source navigation stays deliberate',async({page})=>{await boot(page);await page.locator('.owner360-data-quality button').filter({hasText:'Open source workspace'}).first().click();await page.waitForTimeout(10);expect(await page.evaluate(()=>window.__route)).toBe('admin');expect(await page.evaluate(()=>window.__group)).toBe('operations');});
