import {test,expect} from '@playwright/test';
import fs from 'node:fs';import path from 'node:path';
const source=fs.readFileSync(path.join(process.cwd(),'js/admin-owner-management-command-ui.js'),'utf8');
const now=()=>new Date().toISOString();
const meta=()=>({state:'current',confidence:'high',last_authoritative_update:now(),reason:'All required authoritative sources are current.'});
function fixture(){return{
  ok:true,source_visibility:{jobs:true,finance:true,safety:false,admin:false},source_freshness:{},
  management_metric_confidence:{estimate_to_cash:meta(),recurring_retention:meta(),route_efficiency:{state:'missing',confidence:'low'},capacity_forecast:{state:'missing',confidence:'low'},
    crews_today:meta(),completion_today:meta(),schedule_risk:meta(),revenue:meta(),gross_margin:meta(),receivables:meta(),cash_bank:meta(),recurring_completion:meta(),winter_operations:meta(),fall_cleanup:meta(),equipment_blockers:meta(),finance_readiness:meta()},
  four_season_capacity_forecast:null,route_crew_efficiency_evidence:null,recurring_renewal_retention_workbench:null,
  estimate_to_cash_leakage_workbench:{
    summary:{accepted_estimate_lifecycles:3,accepted_not_scheduled:1,completed_not_invoiced:1,approved_extra_not_billed:1,invoiced_not_collected:1,material_margin_leakage:1,total_open_leakage_signals:5,jobs_evidence_visible:true,finance_evidence_visible:true},
    attention_queue:[
      {signal_type:'completed_not_invoiced',source_module:'finance',source_reference:'WO-356-001',client_name:'Maple Customer',site_name:'Maple Site',amount:650,detail:'Completion/accounting-ready evidence exists without an A/R invoice.',suggested_next_action:'Review invoice readiness and Finance handoff',navigation_target:'finance'},
      {signal_type:'approved_extra_not_billed',source_module:'jobs',source_reference:'CO-356-001',client_name:'Maple Customer',site_name:'Maple Site',amount:175,detail:'Authorized/applied change-order scope is not linked to invoice evidence.',suggested_next_action:'Review change-order invoice evidence',navigation_target:'jobs'},
      {signal_type:'invoiced_not_collected',source_module:'finance',source_reference:'INV-356-001',client_name:'Oak Customer',site_name:'Oak Site',amount:420,detail:'Invoice has a remaining recorded balance after 1 payment application record(s).',suggested_next_action:'Review receivable and payment application evidence',navigation_target:'finance'},
      {signal_type:'material_margin_leakage',source_module:'finance',source_reference:'JOB-356',client_name:'Pine Customer',site_name:'Pine Site',amount:-85,detail:'Recorded actual job profit is negative.',suggested_next_action:'Review estimate assumptions, approved extras, actual cost and billed revenue',navigation_target:'finance'},
      {signal_type:'accepted_not_scheduled',source_module:'jobs',source_reference:'EST-356',client_name:'Elm Customer',site_name:'Elm Site',amount:900,detail:'Accepted estimate has not yet produced a work order/dispatch.',suggested_next_action:'Review scheduling / dispatch readiness',navigation_target:'jobs'}
    ],
    lifecycles:[{estimate_number:'EST-356',work_order_number:'WO-356-001',invoice_number:null,client_name:'Maple Customer',site_name:'Maple Site',accepted_not_scheduled:false,completed_not_invoiced:true,approved_extra_not_billed_count:1,invoiced_not_collected:false,material_margin_leakage:false}],
    margin_boundary:'Material margin leakage is flagged only from strong recorded evidence: negative actual job profit, or simultaneous adverse recorded revenue and cost variance. No dollar or percentage threshold is invented.',
    scheduling_boundary:'Accepted-not-scheduled means accepted customer evidence exists and no active dispatch record is loaded for the resulting work order; an accepted estimate without a work order is also surfaced.',
    billing_boundary:'Completed-not-invoiced uses completion/accounting-ready evidence without an A/R invoice. Approved-extra-not-billed requires authorized/applied change-order scope without linked invoice evidence.',
    collection_boundary:'Invoiced-not-collected uses the recorded A/R balance due and payment-application evidence; it does not initiate reminders, collect payment or mutate provider state.',
    authority_boundary:'Estimate, Jobs/dispatch/production, change-order and Finance records remain their existing authorities. This workbench is analytical only and cannot post accounting, create invoices, apply payments or charge customers.'
  },
  owner_jobs:[],owner_dispatch:[],owner_production:[],owner_profitability:[],owner_timekeeping_summary:[],owner_recurring:[],owner_recurring_visits:[],owner_crews:[],owner_storms:[],owner_storm_routes:[],owner_seasonal_work:[],owner_safety:[],owner_equipment:[],owner_maintenance:[],owner_training_summary:[],owner_workforce_summary:[],owner_receivables:[],owner_bank:[],owner_finance_exceptions:[],owner_close_dashboard:[],owner_workability:[]
}}
async function boot(page,data=fixture()){await page.setViewportSize({width:390,height:844});await page.setContent('<!doctype html><html><body><section id="admin"></section></body></html>');await page.evaluate(payload=>{window.YWIRouter={showSection:s=>window.__route=s};window.YWIAdminHub={open:s=>window.__group=s};window.YWIAPI={loadAdminDirectory:async()=>payload}},data);await page.addScriptTag({content:source});await page.evaluate(()=>window.YWIOwnerManagementCommandUI.mount({api:window.YWIAPI}));await expect(page.locator('#owner356EstimateCash')).toBeVisible();}
test('Build 356 renders leakage signals and lifecycle evidence without Finance mutation',async({page})=>{await boot(page);const h=page.locator('#owner356EstimateCash');await expect(h).toContainText('Accepted not scheduled');await expect(h).toContainText('Completed not invoiced');await expect(h).toContainText('Approved extras not billed');await expect(h).toContainText('Invoiced not collected');await expect(h).toContainText('Margin leakage');await expect(h).toContainText('WO-356-001');await expect(h).toContainText('CO-356-001');await expect(h).toContainText('INV-356-001');await expect(page.locator('.owner356-cash')).toContainText('does not create invoices, post accounting, apply payments, send collection messages or charge customers');expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBeFalsy();});
test('Build 356 hides cross-module evidence when Finance visibility is missing',async({page})=>{const d=fixture();d.source_visibility.finance=false;d.management_metric_confidence.estimate_to_cash={state:'unavailable',confidence:'unavailable',reason:'Finance hidden.'};await boot(page,d);await expect(page.locator('#owner356EstimateCash')).toContainText('requires both Jobs and Finance visibility');await expect(page.locator('#owner356EstimateCash')).not.toContainText('WO-356-001');});
test('Build 356 source navigation stays deliberate',async({page})=>{await boot(page);await page.locator('#owner356EstimateCash button').filter({hasText:'Open Finance'}).first().click();expect(await page.evaluate(()=>window.__route)).toBe('finance');});
