import { test, expect } from '@playwright/test';
import fs from 'node:fs';
const read=(f)=>fs.readFileSync(f,'utf8'); const css=read('style.css'); const index=read('index.html'); const help=read('help.html'); const routes=read('js/public-routes.js'); const portal=read('js/customer-portal.js'); const clean=(html)=>html.replace(/<script\b[\s\S]*?<\/script>/gi,''); const viewports=[{name:'phone',width:390,height:844},{name:'desktop',width:1440,height:960}];
async function noOverflow(page,width){const size=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth}));expect(size.scroll).toBeLessThanOrEqual(Math.max(width,size.client)+1);}
for(const v of viewports){
 test(`app shell is one-H1 and responsive on ${v.name}`,async({page})=>{await page.setViewportSize({width:v.width,height:v.height});await page.setContent(clean(index));await page.addStyleTag({content:css});expect(await page.locator('h1').count()).toBe(1);await expect(page.getByRole('link',{name:'Open online help'})).toBeVisible();await noOverflow(page,v.width);});
 test(`online Help is one-H1 and responsive on ${v.name}`,async({page})=>{await page.setViewportSize({width:v.width,height:v.height});await page.setContent(clean(help));await page.addStyleTag({content:css});expect(await page.locator('h1').count()).toBe(1);expect(await page.locator('meta[name="robots"]').getAttribute('content')).toContain('noindex');await expect(page.getByRole('heading',{name:'Yard Weasels Inc. Online Help'})).toBeVisible();await expect(page.getByRole('link',{name:'Return to app'})).toBeVisible();await noOverflow(page,v.width);});
 test(`public service webpage owns one H1 and responsive canonical on ${v.name}`,async({page})=>{await page.setViewportSize({width:v.width,height:v.height});await page.route('https://layout.test/services/demo',r=>r.fulfill({status:200,contentType:'text/html',body:clean(index)}));await page.goto('https://layout.test/services/demo');await page.addStyleTag({content:css});await page.evaluate(()=>{window.YWIAPI={fetchPublicContent:async()=>({ok:true,route:{route_path:'/services/demo',canonical_url:'https://outside.invalid/services/demo',page_title:'Demo service | Yard Weasels Inc.',meta_description:'Approved demo service page for rendered SEO acceptance.',h1_text:'Approved Southern Ontario Demo Service',page_intro:'Approved public service introduction.',service_name:'Demo Service',location_name:'Southern Ontario',page_body_markdown:'## What to expect\nClear approved service information.',primary_cta_path:'/#quote-intake',local_proof_hint:'Published only after content approval.'},visual:null})};});await page.addScriptTag({content:routes});await expect(page.getByRole('heading',{level:1,name:'Approved Southern Ontario Demo Service'})).toBeVisible();expect(await page.locator('h1').count()).toBe(1);expect(await page.locator('link[rel="canonical"]').getAttribute('href')).toBe('https://layout.test/services/demo');expect(await page.locator('meta[name="robots"]').getAttribute('content')).toContain('index,follow');await noOverflow(page,v.width);});
}
test('customer token portal is noindex and never combines shell H1 with portal H1',async({page})=>{await page.setViewportSize({width:390,height:844});await page.route('https://layout.test/?portal=test-token',r=>r.fulfill({status:200,contentType:'text/html',body:clean(index)}));await page.goto('https://layout.test/?portal=test-token');await page.addStyleTag({content:css});await page.evaluate(()=>{window.YWIAPI={customerPortal:async()=>({ok:false,error:'Portal unavailable for test'})};});await page.addScriptTag({content:portal});await expect(page.locator('meta[name="robots"]')).toHaveAttribute('content',/noindex/);await expect.poll(async()=>page.locator('h1').count()).toBe(1);await noOverflow(page,390);});
