import {test,expect} from '@playwright/test';
import fs from 'node:fs';import path from 'node:path';
const source=fs.readFileSync(path.join(process.cwd(),'js/admin-owner-management-command-ui.js'),'utf8');
const now=()=>new Date().toISOString();
const meta=()=>({state:'current',confidence:'high',last_authoritative_update:now(),reason:'All required authoritative sources are current.'});
function fixture(){return{
  ok:true,source_visibility:{jobs:true,finance:false,safety:false,admin:true},source_freshness:{},
  management_metric_confidence:{utilization_support:meta(),estimate_to_cash:{state:'unavailable',confidence:'unavailable'},recurring_retention:{state:'missing',confidence:'low'},route_efficiency:{state:'missing',confidence:'low'},capacity_forecast:{state:'missing',confidence:'low'},
    crews_today:meta(),completion_today:meta(),schedule_risk:meta(),revenue:{state:'unavailable',confidence:'unavailable'},gross_margin:{state:'unavailable',confidence:'unavailable'},receivables:{state:'unavailable',confidence:'unavailable'},cash_bank:{state:'unavailable',confidence:'unavailable'},recurring_completion:meta(),winter_operations:meta(),fall_cleanup:meta(),equipment_blockers:meta(),workforce_blockers:meta(),finance_readiness:{state:'unavailable',confidence:'unavailable'}},
  four_season_capacity_forecast:null,route_crew_efficiency_evidence:null,recurring_renewal_retention_workbench:null,estimate_to_cash_leakage_workbench:null,
  labour_equipment_fleet_utilization_support:{
    source_queries_ok:true,
    summary:{paid_hours:126.5,job_linked_paid_hours:116.0,paid_hours_without_job_link:10.5,production_labour_hours:112.25,dispatch_items:42,dispatch_items_with_crew_assignment:39,crew_assignment_coverage_percent:92.9,equipment_asset_count:8,equipment_with_recent_recorded_use:6,equipment_no_recent_recorded_use:2,active_equipment_signouts:1,locked_out_assets:1,maintenance_attention_assets:2,replacement_attention_assets:1,fleet_asset_count:3,fleet_known_available:2,fleet_downtime_assets:1,fleet_availability_unknown:0,attention_asset_count:3},
    crew_utilization:[
      {crew_id:'crew-north',crew_name:'Crew North',paid_hours:64.5,job_linked_paid_hours:60,travel_hours:5.5,paid_hours_without_job_link:4.5,production_labour_hours:58.25,dispatch_item_count:21,production_session_count:18,job_link_coverage_percent:93.0},
      {crew_id:'crew-south',crew_name:'Crew South',paid_hours:62,job_linked_paid_hours:56,travel_hours:4.5,paid_hours_without_job_link:6,production_labour_hours:54,dispatch_item_count:21,production_session_count:17,job_link_coverage_percent:90.3}
    ],
    attention_queue:[
      {signal_type:'downtime_or_lockout',equipment_item_id:357,equipment_code:'TRK-357',equipment_name:'Winter Truck 357',attention_reasons:['fleet downtime','equipment locked out'],detail:'fleet downtime · equipment locked out',suggested_next_action:'Review the existing lockout / fleet downtime authority before assignment.',navigation_target:'operations'},
      {signal_type:'maintenance_attention',equipment_item_id:358,equipment_code:'MOW-358',equipment_name:'Mower 358',attention_reasons:['preventive maintenance overdue'],detail:'preventive maintenance overdue',suggested_next_action:'Review the existing preventive-maintenance plan and service-task authority.',navigation_target:'operations'},
      {signal_type:'utilization_evidence_review',equipment_item_id:359,equipment_code:'TRL-359',equipment_name:'Trailer 359',attention_reasons:['no recorded equipment signout in the 30-day window'],detail:'no recorded equipment signout in the 30-day window',suggested_next_action:'Review whether the asset is intentionally spare/seasonal or whether usage evidence is missing.',navigation_target:'operations'}
    ],
    fleet_availability:[
      {equipment_code:'TRK-357',equipment_name:'Winter Truck 357',fleet_operational_status:'downtime',fleet_readiness_status:'blocked',locked_out:true,fleet_downtime:true,last_recorded_use_at:now()},
      {equipment_code:'TRK-358',equipment_name:'Landscape Truck 358',fleet_operational_status:'available',fleet_readiness_status:'ready',locked_out:false,fleet_downtime:false,last_recorded_use_at:now()}
    ],
    labour_boundary:'Labour utilization is crew/business-level recording context only: paid time, job-linked paid time, travel, dispatch assignment coverage and recorded production labour. It does not score, rank or infer individual employee performance.',
    equipment_boundary:'Equipment utilization is based on existing signout evidence. No recorded signout in the 30-day window is an evidence signal only and is not treated as proof that an asset was idle or unnecessary.',
    safety_boundary:'Equipment lockout, fleet downtime and readiness restrictions are operating constraints from their existing authorities. They are never converted into employee performance judgments or used to clear a Safety restriction.',
    maintenance_boundary:'Maintenance and replacement signals reuse recorded preventive-maintenance due states and equipment replacement states. This layer does not complete maintenance, clear lockouts, replace assets, purchase equipment or create vendor commitments.',
    privacy_boundary:'Returned utilization evidence is aggregated by crew and asset. Individual employee names, employee numbers, explanations and other private timekeeping details are not returned by this decision-support layer.',
    authority_boundary:'Read-only management evidence. Timekeeping, dispatch, production, equipment signout, lockout/return-to-service, maintenance and fleet workflows remain the existing mutation authorities.'
  },
  owner_jobs:[],owner_dispatch:[],owner_production:[],owner_profitability:[],owner_timekeeping_summary:[],owner_recurring:[],owner_recurring_visits:[],owner_crews:[],owner_storms:[],owner_storm_routes:[],owner_seasonal_work:[],owner_safety:[],owner_equipment:[],owner_maintenance:[],owner_training_summary:[],owner_workforce_summary:[],owner_receivables:[],owner_bank:[],owner_finance_exceptions:[],owner_close_dashboard:[],owner_workability:[],owner_equipment_use:[],owner_fleet:[]
}}
async function boot(page,data=fixture()){await page.setViewportSize({width:390,height:844});await page.setContent('<!doctype html><html><body><section id="admin"></section></body></html>');await page.evaluate(payload=>{window.YWIRouter={showSection:s=>window.__route=s};window.YWIAdminHub={open:s=>window.__group=s};window.YWIAPI={loadAdminDirectory:async()=>payload}},data);await page.addScriptTag({content:source});await page.evaluate(()=>window.YWIOwnerManagementCommandUI.mount({api:window.YWIAPI}));await expect(page.locator('#owner357Utilization')).toBeVisible();}
test('Build 357 renders crew-level and asset utilization evidence without employee scoring',async({page})=>{await boot(page);const h=page.locator('#owner357Utilization');await expect(h).toContainText('Paid time, 30d');await expect(h).toContainText('Job-linked paid time');await expect(h).toContainText('Crew North');await expect(h).toContainText('TRK-357');await expect(h).toContainText('fleet downtime');await expect(h).toContainText('MOW-358');await expect(h).toContainText('no recorded equipment signout in the 30-day window');await expect(page.locator('.owner357-utilization')).toContainText('does not score employees');await expect(h).toContainText('not treated as proof that an asset was idle or unnecessary');await expect(h).not.toContainText('EMP-357-SECRET');await expect(h).not.toContainText('Alice Individual Worker');expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBeFalsy();});
test('Build 357 keeps paid-time evidence permission scoped',async({page})=>{const d=fixture();d.source_visibility.admin=false;d.management_metric_confidence.utilization_support={state:'unavailable',confidence:'unavailable',reason:'Admin hidden.'};await boot(page,d);await expect(page.locator('#owner357Utilization')).toContainText('requires Jobs visibility and Admin management access');await expect(page.locator('#owner357Utilization')).not.toContainText('Crew North');});
test('Build 357 navigation stays deliberate',async({page})=>{await boot(page);await page.locator('.owner357-utilization button').filter({hasText:'Open Operations'}).first().click();await page.waitForTimeout(10);expect(await page.evaluate(()=>window.__route)).toBe('admin');expect(await page.evaluate(()=>window.__group)).toBe('operations');});
