import {test,expect} from '@playwright/test';
import fs from 'node:fs';import path from 'node:path';
const source=fs.readFileSync(path.join(process.cwd(),'js/admin-owner-management-command-ui.js'),'utf8');
const now=()=>new Date().toISOString();
const meta=()=>({state:'current',confidence:'high',last_authoritative_update:now(),reason:'Required source queries succeeded.'});
function fixture(){return{
  ok:true,source_visibility:{jobs:true,finance:false,safety:false,admin:false},source_freshness:{},
  management_metric_confidence:{stock_readiness:meta(),utilization_support:{state:'unavailable',confidence:'unavailable'},estimate_to_cash:{state:'unavailable',confidence:'unavailable'},recurring_retention:{state:'missing',confidence:'low'},route_efficiency:{state:'missing',confidence:'low'},capacity_forecast:{state:'missing',confidence:'low'},crews_today:meta(),completion_today:meta(),schedule_risk:meta(),revenue:{state:'unavailable',confidence:'unavailable'},gross_margin:{state:'unavailable',confidence:'unavailable'},receivables:{state:'unavailable',confidence:'unavailable'},cash_bank:{state:'unavailable',confidence:'unavailable'},recurring_completion:meta(),winter_operations:meta(),fall_cleanup:meta(),equipment_blockers:meta(),workforce_blockers:{state:'unavailable',confidence:'unavailable'},finance_readiness:{state:'unavailable',confidence:'unavailable'}},
  four_season_capacity_forecast:null,route_crew_efficiency_evidence:null,recurring_renewal_retention_workbench:null,estimate_to_cash_leakage_workbench:null,labour_equipment_fleet_utilization_support:null,
  materials_consumables_seasonal_stock_readiness:{
    source_queries_ok:true,forecast_start:'2026-09-29',forecast_end:'2026-10-13',
    summary:{active_material_count:6,tracked_material_count:6,materials_with_quantified_14_day_demand:3,shortage_within_7_days:1,shortage_within_14_days:1,reorder_review_count:2,unit_comparison_required_count:1,unscheduled_material_plan_line_count:1,uncatalogued_scheduled_plan_line_count:1,recurring_visit_count_14_days:4,recurring_visits_with_quantified_material_plan:1,recurring_visits_without_quantified_material_plan:3,seasonal_material_readiness_task_count:2},
    attention_queue:[
      {signal_type:'shortage_within_7_days',material_id:'salt-358',sku:'SALT-358',item_name:'Road Salt',seasonal_bucket:'winter',stock_on_hand:100,stock_unit:'kg',planned_demand_7:140,planned_demand_14:180,projected_on_hand_14:-80,shortage_date:'2026-10-02',recorded_reorder_quantity:500,preferred_vendor_name:'Seasonal Supply',detail:'Recorded planned demand exceeds current on-hand stock by 2026-10-02.',suggested_next_action:'Review the canonical Materials Control stock, planned work and recorded reorder settings before purchasing.'},
      {signal_type:'unit_comparison_required',material_id:'mulch-358',sku:'MULCH-358',item_name:'Black Mulch',seasonal_bucket:'spring_summer',stock_on_hand:5,stock_unit:'m3',planned_demand_7:0,planned_demand_14:0,projected_on_hand_14:null,shortage_date:null,recorded_reorder_quantity:10,preferred_vendor_name:'Landscape Supply',detail:'One or more scheduled material plans use a unit that does not match the catalog stock unit; projected stock is withheld.',suggested_next_action:'Review the canonical Materials Control stock, planned work and recorded reorder settings before purchasing.'},
      {signal_type:'reorder_risk',material_id:'bags-358',sku:'BAG-358',item_name:'Leaf Collection Bags',seasonal_bucket:'fall',stock_on_hand:45,stock_unit:'ea',planned_demand_7:10,planned_demand_14:30,projected_on_hand_14:15,shortage_date:null,recorded_reorder_quantity:100,preferred_vendor_name:'Yard Supply',detail:'Current or projected on-hand evidence reaches the recorded reorder point.',suggested_next_action:'Review the canonical Materials Control stock, planned work and recorded reorder settings before purchasing.'}
    ],
    seasonal_summary:[
      {season:'spring_summer',material_count:2,attention_count:1,shortage_count:0,reorder_review_count:0,unit_comparison_required_count:1},
      {season:'fall',material_count:1,attention_count:1,shortage_count:0,reorder_review_count:1,unit_comparison_required_count:0},
      {season:'winter',material_count:2,attention_count:1,shortage_count:1,reorder_review_count:1,unit_comparison_required_count:0},
      {season:'four_season',material_count:1,attention_count:0,shortage_count:0,reorder_review_count:0,unit_comparison_required_count:0}
    ],
    recurring_demand_coverage:[
      {occurrence_key:'RSA-358:2026-10-01',agreement_code:'RSA-358',service_name:'Weekly Mowing',service_program_type:'mowing',service_date:'2026-10-01',material_plan_coverage:'unquantified'},
      {occurrence_key:'RSA-359:2026-10-04',agreement_code:'RSA-359',service_name:'Fall Cleanup',service_program_type:'fall_cleanup',service_date:'2026-10-04',material_plan_coverage:'unquantified'}
    ],
    demand_boundary:'Quantified demand comes only from planned Landscape Material Estimator lines whose work order has an active dispatch inside the 14-day window. The same plan is scheduled once at its earliest active dispatch and is not multiplied across repeated dispatch rows.',
    recurring_boundary:'Upcoming recurring visits are checked for a linked dispatch/work order with a quantified material plan. Visits without that chain are shown as unquantified demand coverage; no per-visit material amount is invented.',
    unit_boundary:'Projected on-hand and shortage timing are calculated only when the planned material unit exactly matches the canonical catalog stock unit after simple text normalization. No hidden unit conversion is performed.',
    seasonal_boundary:'Stock context distinguishes spring/summer landscaping and lawn materials, fall cleanup supplies, winter salt/de-icer/traction materials, and general four-season stock using recorded catalog names/categories. Classification is advisory and does not rewrite catalog data.',
    purchasing_boundary:'Reorder signals reuse current stock, planned demand and recorded reorder/target settings. They do not create purchase orders, contact suppliers, reserve stock, or create vendor commitments.',
    authority_boundary:'Read-only management evidence. Materials catalog, receipts, issues, adjustments, Landscape Material Estimator plans, recurring service and dispatch remain their existing authorities.'
  },
  owner_jobs:[],owner_dispatch:[],owner_production:[],owner_profitability:[],owner_timekeeping_summary:[],owner_recurring:[],owner_recurring_visits:[],owner_crews:[],owner_storms:[],owner_storm_routes:[],owner_seasonal_work:[],owner_safety:[],owner_equipment:[],owner_maintenance:[],owner_training_summary:[],owner_workforce_summary:[],owner_receivables:[],owner_bank:[],owner_finance_exceptions:[],owner_close_dashboard:[],owner_workability:[],owner_equipment_use:[],owner_fleet:[],owner_material_stock:[],owner_material_plans:[]
}}
async function boot(page,data=fixture()){await page.setViewportSize({width:390,height:844});await page.setContent('<!doctype html><html><body><section id="admin"></section></body></html>');await page.evaluate(payload=>{window.YWIRouter={showSection:s=>window.__route=s};window.YWIAdminHub={open:s=>window.__group=s};window.YWIAPI={loadAdminDirectory:async()=>payload}},data);await page.addScriptTag({content:source});await page.evaluate(()=>window.YWIOwnerManagementCommandUI.mount({api:window.YWIAPI}));await expect(page.locator('#owner358Stock')).toBeVisible();}
test('Build 358 renders seasonal shortage, reorder and recurring coverage evidence',async({page})=>{await boot(page);const h=page.locator('#owner358Stock');await expect(h).toContainText('Shortage ≤7 days');await expect(h).toContainText('SALT-358');await expect(h).toContainText('shortage 2026-10-02');await expect(h).toContainText('MULCH-358');await expect(h).toContainText('projected stock is withheld');await expect(h).toContainText('BAG-358');await expect(h).toContainText('spring / summer');await expect(h).toContainText('fall');await expect(h).toContainText('winter');await expect(h).toContainText('RSA-358');await expect(h).toContainText('quantified material plan not linked');await expect(h).toContainText('No hidden unit conversion is performed');await expect(page.locator('.owner358-stock')).toContainText('does not create purchase orders, contact suppliers, reserve stock or create vendor commitments');expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBeFalsy();});
test('Build 358 withholds stock facts when canonical source queries fail',async({page})=>{const d=fixture();d.materials_consumables_seasonal_stock_readiness.source_queries_ok=false;await boot(page,d);await expect(page.locator('#owner358Stock')).toContainText('source queries failed');await expect(page.locator('#owner358Stock')).not.toContainText('SALT-358');});
test('Build 358 stays permission scoped',async({page})=>{const d=fixture();d.source_visibility.jobs=false;await boot(page,d);await expect(page.locator('#owner358Stock')).toContainText('requires Jobs visibility');await expect(page.locator('#owner358Stock')).not.toContainText('SALT-358');});
test('Build 358 opens canonical Jobs materials surface',async({page})=>{await boot(page);await page.locator('.owner358-stock button').filter({hasText:'Open Materials'}).first().click();expect(await page.evaluate(()=>window.__route)).toBe('jobs');});
