import {test,expect} from '@playwright/test';
import fs from 'node:fs';import path from 'node:path';
const source=fs.readFileSync(path.join(process.cwd(),'js/admin-owner-management-command-ui.js'),'utf8');
const now=()=>new Date().toISOString();
const meta=()=>({state:'current',confidence:'high',last_authoritative_update:now(),reason:'Workability, dispatch and production sources are current.'});
function fixture(){return{
  ok:true,source_visibility:{jobs:true,finance:false,safety:false,admin:false},source_freshness:{},
  management_metric_confidence:{
    workability_recovery_outcomes:meta(),data_quality_reconciliation:{state:'missing',confidence:'low'},communication_readiness:{state:'missing',confidence:'low'},
    stock_readiness:{state:'missing',confidence:'low'},utilization_support:{state:'missing',confidence:'low'},estimate_to_cash:{state:'unavailable',confidence:'unavailable'},
    recurring_retention:{state:'missing',confidence:'low'},route_efficiency:{state:'missing',confidence:'low'},capacity_forecast:{state:'missing',confidence:'low'},
    crews_today:meta(),completion_today:meta(),schedule_risk:meta(),revenue:{state:'unavailable',confidence:'unavailable'},gross_margin:{state:'unavailable',confidence:'unavailable'},
    receivables:{state:'unavailable',confidence:'unavailable'},cash_bank:{state:'unavailable',confidence:'unavailable'},labour_utilization:{state:'unavailable',confidence:'unavailable'},
    recurring_completion:meta(),winter_operations:meta(),fall_cleanup:meta(),safety_blockers:{state:'unavailable',confidence:'unavailable'},
    equipment_blockers:meta(),workforce_blockers:{state:'unavailable',confidence:'unavailable'},finance_readiness:{state:'unavailable',confidence:'unavailable'}
  },
  four_season_capacity_forecast:null,route_crew_efficiency_evidence:null,recurring_renewal_retention_workbench:null,estimate_to_cash_leakage_workbench:null,
  labour_equipment_fleet_utilization_support:null,materials_consumables_seasonal_stock_readiness:null,customer_communication_readiness_queue:null,
  data_quality_duplicate_orphan_reconciliation:null,
  workability_schedule_recovery_outcomes:{
    source_queries_ok:true,
    summary:{affected_decision_count:4,rescheduled_count:3,explicit_workable_or_caution_schedule_count:2,production_started_count:2,completed_count:1,unresolved_count:2,avg_decision_to_replan_hours:3.5,avg_decision_to_workable_schedule_hours:18,avg_decision_to_production_start_hours:22,avg_decision_to_completion_hours:25},
    recovery_outcomes:[
      {observation_code:'WX-364-1',decision_id:'dec-1',decision_state:'reschedule',decision_at:'2026-10-01T10:00:00Z',decision_reason:'Rain and saturated ground',work_order_number:'WO-364-1',site_name:'Maple Site',service_context:'mowing_landscaping',season_context:'spring_summer',recovery_dispatch_id:'disp-new-1',recovery_dispatch_status:'rescheduled',recovery_workability_state:'workable',recovery_scheduled_start:'2026-10-02T08:00:00Z',production_session_id:'prod-1',production_started_at:'2026-10-02T08:20:00Z',completion_session_id:'prod-1',completed_at:'2026-10-02T11:00:00Z',outcome_state:'completed_after_constraint',decision_to_replan_hours:2,decision_to_workable_schedule_hours:22,decision_to_production_start_hours:22.33,decision_to_completion_hours:25,source_links:[]},
      {observation_code:'WX-364-2',decision_id:'dec-2',decision_state:'blocked',decision_at:'2026-10-01T12:00:00Z',decision_reason:'Freezing rain / ice',work_order_number:'WO-364-2',site_name:'Winter Route',service_context:'snow_clearing_removal',season_context:'winter',recovery_dispatch_id:'disp-new-2',recovery_dispatch_status:'rescheduled',recovery_workability_state:'not_assessed',recovery_scheduled_start:'2026-10-02T05:00:00Z',production_session_id:null,production_started_at:null,completed_at:null,outcome_state:'rescheduled_without_explicit_workability',decision_to_replan_hours:5,decision_to_workable_schedule_hours:null,decision_to_production_start_hours:null,decision_to_completion_hours:null,source_links:[]},
      {observation_code:'WX-364-3',decision_id:'dec-3',decision_state:'postpone',decision_at:'2026-10-02T09:00:00Z',decision_reason:'High wind',work_order_number:'WO-364-3',site_name:'Fall Site',service_context:'fall_cleanup',season_context:'fall',recovery_dispatch_id:null,recovery_dispatch_status:null,recovery_workability_state:null,recovery_scheduled_start:null,production_session_id:null,production_started_at:null,completed_at:null,outcome_state:'unresolved',decision_to_replan_hours:null,decision_to_workable_schedule_hours:null,decision_to_production_start_hours:null,decision_to_completion_hours:null,source_links:[]}
    ],
    seasonal_outcomes:[
      {season:'spring_summer',affected_count:1,explicit_workable_or_caution_schedule_count:1,production_started_count:1,completed_count:1,unresolved_count:0,avg_decision_to_replan_hours:2,avg_decision_to_workable_schedule_hours:22,avg_decision_to_production_start_hours:22.33,avg_decision_to_completion_hours:25},
      {season:'fall',affected_count:1,explicit_workable_or_caution_schedule_count:0,production_started_count:0,completed_count:0,unresolved_count:1,avg_decision_to_replan_hours:null,avg_decision_to_workable_schedule_hours:null,avg_decision_to_production_start_hours:null,avg_decision_to_completion_hours:null},
      {season:'winter',affected_count:1,explicit_workable_or_caution_schedule_count:0,production_started_count:0,completed_count:0,unresolved_count:1,avg_decision_to_replan_hours:5,avg_decision_to_workable_schedule_hours:null,avg_decision_to_production_start_hours:null,avg_decision_to_completion_hours:null},
      {season:'four_season',affected_count:1,explicit_workable_or_caution_schedule_count:1,production_started_count:1,completed_count:0,unresolved_count:0,avg_decision_to_replan_hours:3.5,avg_decision_to_workable_schedule_hours:14,avg_decision_to_production_start_hours:18,avg_decision_to_completion_hours:null}
    ],
    decision_outcomes:[],
    unresolved_queue:[
      {observation_code:'WX-364-2',decision_state:'blocked',decision_reason:'Freezing rain / ice',work_order_number:'WO-364-2',outcome_state:'rescheduled_without_explicit_workability',recovery_scheduled_start:'2026-10-02T05:00:00Z'},
      {observation_code:'WX-364-3',decision_state:'postpone',decision_reason:'High wind',work_order_number:'WO-364-3',outcome_state:'unresolved',recovery_scheduled_start:null}
    ],
    workability_boundary:'Only recorded human/source workability decisions with postpone, reschedule or blocked state enter this outcome view. The workbench never creates or revises a weather/workability verdict.',
    recovery_boundary:'A replacement dispatch is not called workable unless its recorded workability_state is explicitly workable or caution. A reschedule without that evidence remains rescheduled_without_explicit_workability.',
    timing_boundary:'Decision-to-replan measures when a replacement dispatch record was created/updated. Decision-to-workable-schedule measures the scheduled service start of the first later dispatch explicitly marked workable/caution. Production start and completion use recorded production timestamps.',
    seasonal_boundary:'Outcome cohorts retain spring/summer landscaping/lawn, fall cleanup/leaf, winter snow/ice and four-season context from recorded service/season evidence. No external weather provider is introduced.',
    automation_boundary:'Read-only outcome learning. This layer cannot reschedule work, change dispatch, send customer messages, alter workability decisions, dispatch crews, clear Safety restrictions or mutate provider state.',
    authority_boundary:'Workability decisions remain human/source-authoritative; Dispatch remains the schedule authority; Production remains execution/completion authority.'
  },
  owner_jobs:[],owner_dispatch:[],owner_production:[],owner_profitability:[],owner_timekeeping_summary:[],owner_recurring:[],owner_recurring_visits:[],owner_crews:[],owner_storms:[],owner_storm_routes:[],owner_seasonal_work:[],owner_safety:[],owner_equipment:[],owner_maintenance:[],owner_training_summary:[],owner_workforce_summary:[],owner_receivables:[],owner_bank:[],owner_finance_exceptions:[],owner_close_dashboard:[],owner_workability:[],owner_equipment_use:[],owner_fleet:[],owner_material_stock:[],owner_material_plans:[],owner_crm_followups:[],owner_notification_delivery:[],owner_closeouts:[],owner_crm_properties:[]
}}
async function boot(page,data=fixture()){await page.setViewportSize({width:390,height:844});await page.setContent('<!doctype html><html><body><section id="admin"></section></body></html>');await page.evaluate(payload=>{window.YWIRouter={showSection:s=>window.__route=s};window.YWIAdminHub={open:s=>window.__group=s};window.YWIAPI={loadAdminDirectory:async()=>payload}},data);await page.addScriptTag({content:source});await page.evaluate(()=>window.YWIOwnerManagementCommandUI.mount({api:window.YWIAPI}));await expect(page.locator('#owner364WorkabilityRecovery')).toBeVisible();}
test('Build 364 renders recovery milestones without calling an unassessed reschedule workable',async({page})=>{await boot(page);const h=page.locator('#owner364WorkabilityRecovery');await expect(h).toContainText('Affected decisions');await expect(h).toContainText('WO-364-1');await expect(h).toContainText('COMPLETED AFTER CONSTRAINT');await expect(h).toContainText('WO-364-2');await expect(h).toContainText('RESCHEDULED WITHOUT EXPLICIT WORKABILITY');await expect(h).toContainText('No later recovery milestone recorded');await expect(h).toContainText('spring / summer');await expect(h).toContainText('winter');await expect(h).toContainText('A replacement dispatch is not called workable unless');await expect(page.locator('.owner364-workability-recovery')).toContainText('Outcome learning only');expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBeFalsy();});
test('Build 364 withholds outcome facts when canonical reads fail',async({page})=>{const d=fixture();d.workability_schedule_recovery_outcomes.source_queries_ok=false;await boot(page,d);await expect(page.locator('#owner364WorkabilityRecovery')).toContainText('source queries failed');await expect(page.locator('#owner364WorkabilityRecovery')).not.toContainText('WO-364-1');});
test('Build 364 remains Jobs scoped',async({page})=>{const d=fixture();d.source_visibility.jobs=false;await boot(page,d);await expect(page.locator('#owner364WorkabilityRecovery')).toContainText('requires Jobs');await expect(page.locator('#owner364WorkabilityRecovery')).not.toContainText('WO-364-1');});
test('Build 364 source navigation stays deliberate',async({page})=>{await boot(page);await page.locator('.owner364-workability-recovery button').filter({hasText:'Open Workability'}).first().click();await page.waitForTimeout(10);expect(await page.evaluate(()=>window.__route)).toBe('admin');expect(await page.evaluate(()=>window.__group)).toBe('operations');});
