name = "devilndove-site"
compatibility_date = "2026-04-08"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "devilndove-prod"
database_id = "0dc8fa3e-319c-45f7-a515-34c8acd89fcf"

[[r2_buckets]]
binding = "PRODUCT_MEDIA_BUCKET"
bucket_name = "devilndove-toolshed-images"
preview_bucket_name = "devilndove-toolshed-images"
