-- =========================================================
-- sql/037_security_rls_verification_notes.sql
-- Purpose:
-- - Record the intended backend/RLS verification model for YWI HSE
-- - Tie role/site checks to the helper SQL and current frontend security tiers
-- - Use as a deployment checklist before production rollout
-- =========================================================

-- Recommended checks before production:
-- 1) profiles rows are auto-created from auth.users and remain active-aware
-- 2) role_rank(), profile_role_rank(), site_assignment_role_rank(), and effective_site_role_rank()
--    match the active frontend role model
-- 3) admin-only writes require admin rank in Edge Functions and any SQL policies
-- 4) supervisor/hse/job_admin/admin directory reads are validated server-side
-- 5) employee users can only see their own profile and allowed submissions
-- 6) supervisor users can see employee records but not modify admin-only fields unless explicitly allowed
-- 7) admin users can see and manage worker, supervisor, and admin records
-- 8) site assignment reads/writes are constrained by effective site role rank
-- 9) all review-submission and admin-manage functions validate JWT and profile is_active=true
-- 10) storage uploads only accept authenticated submission-linked image writes
