-- File: sql/046_account_validation_and_notifications.sql
-- Brief description: Safe account validation and admin notification upgrade.
-- Adds email/phone validation fields and creates/updates admin_notifications
-- without assuming a pre-existing status column.

begin;

-- =====================================================
-- 1) PROFILES: EMAIL / PHONE VALIDATION FIELDS
-- =====================================================

alter table if exists public.profiles
  add column if not exists email_verified boolean default false;

alter table if exists public.profiles
  add column if not exists phone_verified boolean default false;

alter table if exists public.profiles
  add column if not exists phone text;

alter table if exists public.profiles
  add column if not exists phone_validation_requested_at timestamptz;

alter table if exists public.profiles
  add column if not exists email_validation_requested_at timestamptz;

alter table if exists public.profiles
  add column if not exists validation_notes text;

-- =====================================================
-- 2) ADMIN NOTIFICATIONS TABLE
-- =====================================================

create table if not exists public.admin_notifications (
  id bigint generated by default as identity primary key,
  notification_type text not null,
  title text not null,
  message text,
  target_role text,
  target_profile_id uuid,
  related_table text,
  related_id text,
  status text not null default 'pending',
  payload jsonb not null default '{}'::jsonb,
  created_by uuid,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  resolved_at timestamptz
);

-- Ensure newer columns exist even if table already existed in an older form
alter table if exists public.admin_notifications
  add column if not exists notification_type text;

alter table if exists public.admin_notifications
  add column if not exists title text;

alter table if exists public.admin_notifications
  add column if not exists message text;

alter table if exists public.admin_notifications
  add column if not exists target_role text;

alter table if exists public.admin_notifications
  add column if not exists target_profile_id uuid;

alter table if exists public.admin_notifications
  add column if not exists related_table text;

alter table if exists public.admin_notifications
  add column if not exists related_id text;

alter table if exists public.admin_notifications
  add column if not exists status text default 'pending';

alter table if exists public.admin_notifications
  add column if not exists payload jsonb not null default '{}'::jsonb;

alter table if exists public.admin_notifications
  add column if not exists created_by uuid;

alter table if exists public.admin_notifications
  add column if not exists created_at timestamptz not null default now();

alter table if exists public.admin_notifications
  add column if not exists read_at timestamptz;

alter table if exists public.admin_notifications
  add column if not exists resolved_at timestamptz;

-- Backfill any null status values safely
update public.admin_notifications
set status = 'pending'
where status is null;

-- =====================================================
-- 3) OPTIONAL CONSTRAINTS
-- =====================================================

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'admin_notifications_status_check'
  ) then
    alter table public.admin_notifications
      add constraint admin_notifications_status_check
      check (status in ('pending', 'read', 'resolved', 'dismissed'));
  end if;
end $$;

-- =====================================================
-- 4) HELPER INDEXES
-- =====================================================

create index if not exists idx_admin_notifications_status
  on public.admin_notifications(status);

create index if not exists idx_admin_notifications_target_role
  on public.admin_notifications(target_role);

create index if not exists idx_admin_notifications_target_profile_id
  on public.admin_notifications(target_profile_id);

create index if not exists idx_admin_notifications_created_at
  on public.admin_notifications(created_at desc);

-- =====================================================
-- 5) SIMPLE NOTIFICATION VIEW
-- =====================================================

drop view if exists public.v_admin_notifications;

create view public.v_admin_notifications as
select
  n.id,
  n.notification_type,
  n.title,
  n.message,
  n.target_role,
  n.target_profile_id,
  n.related_table,
  n.related_id,
  n.status,
  n.payload,
  n.created_by,
  creator.full_name as created_by_name,
  creator.email as created_by_email,
  n.created_at,
  n.read_at,
  n.resolved_at
from public.admin_notifications n
left join public.profiles creator
  on creator.id = n.created_by;

-- =====================================================
-- 6) SAFE RLS ENABLE
-- =====================================================

alter table public.admin_notifications enable row level security;

-- Remove old policies if they exist
drop policy if exists "admin_notifications_select_policy" on public.admin_notifications;
drop policy if exists "admin_notifications_insert_policy" on public.admin_notifications;
drop policy if exists "admin_notifications_update_policy" on public.admin_notifications;

-- Admin / HSE / Job Admin / Onsite Admin can read
create policy "admin_notifications_select_policy"
on public.admin_notifications
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'hse', 'job_admin', 'onsite_admin', 'supervisor')
  )
);

-- Any authenticated app process/user can insert their own created notifications
create policy "admin_notifications_insert_policy"
on public.admin_notifications
for insert
to authenticated
with check (
  auth.uid() is not null
);

-- Higher roles can update status/read/resolved
create policy "admin_notifications_update_policy"
on public.admin_notifications
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'hse', 'job_admin', 'onsite_admin', 'supervisor')
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'hse', 'job_admin', 'onsite_admin', 'supervisor')
  )
);

-- =====================================================
-- 7) TEST INSERT TO VERIFY STRUCTURE
-- =====================================================
-- This does not run automatically; it is just a reference example.
-- insert into public.admin_notifications (
--   notification_type,
--   title,
--   message,
--   target_role,
--   related_table,
--   related_id,
--   status,
--   payload,
--   created_by
-- ) values (
--   'phone_verification',
--   'Phone verification requested',
--   'A user requested phone verification.',
--   'admin',
--   'profiles',
--   auth.uid()::text,
--   'pending',
--   jsonb_build_object('source', 'account-maintenance'),
--   auth.uid()
-- );

commit;
