begin;
-- Schema 193 — online Help, documentation hygiene, public search and one-H1 release authority.
insert into public.it_readiness_check_registry(check_key,check_group,check_title,severity_if_failed,action_hint,route_hint,sort_order,is_enabled)
values('online_help_public_search_hygiene','Web / Help','Online Help, public search and rendered one-H1 authority','error','Keep /help.html synchronized with current workflows; keep operational Help and token portals noindex; require one rendered H1, same-origin canonicals, canonical-only truthful sitemap entries, and phone/desktop browser acceptance for public pages.','Online Help + public website source gates',45,true)
on conflict(check_key) do update set check_group=excluded.check_group,check_title=excluded.check_title,severity_if_failed=excluded.severity_if_failed,action_hint=excluded.action_hint,route_hint=excluded.route_hint,sort_order=excluded.sort_order,is_enabled=excluded.is_enabled,updated_at=now();
insert into public.admin_scorecard_progress_rails(rail_key,rail_area,rail_title,rail_status,progress_percent,current_value,target_value,next_action_hint,owner_hint,sort_order,metadata)
values('schema193_help_seo_hygiene','admin','Online Help, documentation hygiene and public search authority','active',80,8,10,'Verify Help/SEO source and rendered phone/desktop gates, Schema 193 current, dev/main parity, release evidence and branch cleanup. Do not close business acceptance rails.','Admin / I.T. / Web',113,jsonb_build_object('schema',193,'business_rail_auto_close',false,'finance_mutation',false,'payment_provider_mutation',false,'production_promotion',false,'source_only_product_behavior',true))
on conflict(rail_key) do update set rail_area=excluded.rail_area,rail_title=excluded.rail_title,rail_status=excluded.rail_status,progress_percent=excluded.progress_percent,current_value=excluded.current_value,target_value=excluded.target_value,next_action_hint=excluded.next_action_hint,owner_hint=excluded.owner_hint,sort_order=excluded.sort_order,metadata=excluded.metadata,updated_at=now();
insert into public.it_scorecard_rail_resolution_contracts(rail_key,resolution_class,requires_human,requires_external,auto_close_allowed,resolution_note,introduced_by_schema)
values('schema193_help_seo_hygiene','build_acceptance',false,false,false,'Close this technical release rail only after current Help/search/H1 source gates, rendered phone/desktop acceptance, live schema convergence, dev/main parity, release evidence and cleanup. No business acceptance auto-close is authorized.',193)
on conflict(rail_key) do update set resolution_class=excluded.resolution_class,requires_human=excluded.requires_human,requires_external=excluded.requires_external,auto_close_allowed=excluded.auto_close_allowed,resolution_note=excluded.resolution_note,introduced_by_schema=excluded.introduced_by_schema,updated_at=now();
create or replace function public.ywi_help_seo_release_assertions() returns table(assertion_key text,assertion_status text,assertion_detail text) language sql security definer set search_path=public,pg_temp as $$
 select 'prior_pg_net_runtime_constraint_green',case when not exists(select 1 from public.ywi_pg_net_runtime_constraint_assertions() where assertion_status<>'passed') then 'passed' else 'failed' end,'Prior runtime dependency assertions remain green.'
 union all select 'business_acceptance_rails_untouched',case when (select count(*) from public.v_it_open_rail_acceptance_readiness where rail_status<>'complete')=11 then 'passed' else 'failed' end,'All existing human/provider/accounting/content acceptance rails remain open.'
 union all select 'finance_execution_provider_off',case when not exists(select 1 from public.finance_job_completion_posting_execution_controls where execution_enabled=true or provider_mutation_enabled=true) then 'passed' else 'failed' end,'Finance posting execution and provider mutation remain OFF.'
 union all select 'help_seo_rail_present',case when exists(select 1 from public.admin_scorecard_progress_rails where rail_key='schema193_help_seo_hygiene' and rail_status='active') then 'passed' else 'failed' end,'The source-facing Help/search release rail is present for explicit release closure.';
$$;
revoke all on function public.ywi_help_seo_release_assertions() from public,anon,authenticated; grant execute on function public.ywi_help_seo_release_assertions() to service_role;
create or replace view public.v_schema_drift_status with (security_invoker=true) as select 193::int as expected_schema_version,coalesce(max(schema_version) filter(where status='applied'),0)::int as latest_applied_schema_version,case when coalesce(max(schema_version) filter(where status='applied'),0)>=193 then 'current' else 'behind' end::text as drift_status,case when coalesce(max(schema_version) filter(where status='applied'),0)>=193 then 'Live database is at or ahead of the repo schema marker.' else 'Live database is behind the deployed app. Apply migrations through the current schema in order.' end::text as message,now() as checked_at from public.app_schema_versions;
revoke all on table public.v_schema_drift_status from public,anon,authenticated; grant select on table public.v_schema_drift_status to service_role;
insert into public.app_schema_versions(schema_version,migration_key,schema_name,release_label,description,status,notes) values(193,'193_help_seo_hygiene','193_help_seo_hygiene.sql','2026-09-03g','Records current online Help, documentation hygiene, public search and one-H1 source release authority.','applied','No business data mutation. Finance/provider execution remains OFF; business acceptance remains evidence-gated; Production promotion remains manual.') on conflict(schema_version) do update set migration_key=excluded.migration_key,schema_name=excluded.schema_name,release_label=excluded.release_label,description=excluded.description,status=excluded.status,notes=excluded.notes,applied_at=now();
commit;
