begin;

-- Schema 198 — Supabase Auth security evidence authority.
-- Current leaked-password-protection and MFA follow-ups remain open unless recent,
-- authoritative external evidence proves the control is secure. Historical advisor
-- rows and absence of an advisor warning are explicitly insufficient proof.
-- No Auth setting, business acceptance rail, Finance/provider control, or Production
-- promotion is changed by this migration.

create table if not exists public.it_auth_security_evidence (
  evidence_id bigint generated by default as identity primary key,
  control_key text not null check (control_key in ('leaked_password_protection','mfa_options')),
  evidence_source text not null check (evidence_source in ('supabase_dashboard','supabase_management_api','supabase_advisor','manual_external')),
  observed_state text not null check (observed_state in ('enabled','disabled','configured','not_configured','unknown')),
  verification_status text not null check (verification_status in ('verified_secure','verified_followup','informational','unverified')),
  is_authoritative boolean not null default false,
  observed_at timestamptz not null,
  expires_at timestamptz,
  evidence_reference text,
  evidence_detail jsonb not null default '{}'::jsonb,
  recorded_by_profile_id uuid,
  introduced_by_schema int not null default 198,
  created_at timestamptz not null default now(),
  check (expires_at is null or expires_at > observed_at),
  check (
    verification_status <> 'verified_secure'
    or (
      is_authoritative = true
      and evidence_source in ('supabase_dashboard','supabase_management_api','manual_external')
      and observed_state in ('enabled','configured')
    )
  )
);

create index if not exists idx_it_auth_security_evidence_current
  on public.it_auth_security_evidence(control_key, observed_at desc, evidence_id desc);

alter table public.it_auth_security_evidence enable row level security;
revoke all on table public.it_auth_security_evidence from public,anon,authenticated;
grant select,insert,update on table public.it_auth_security_evidence to service_role;

create or replace view public.v_it_auth_security_evidence_current
with (security_invoker=true)
as
with controls(control_key,control_title,secure_state_hint) as (
  values
    ('leaked_password_protection'::text,'Leaked-password protection'::text,'enabled'::text),
    ('mfa_options'::text,'MFA options'::text,'configured'::text)
), latest as (
  select distinct on (e.control_key)
    e.control_key,e.evidence_id,e.evidence_source,e.observed_state,e.verification_status,
    e.is_authoritative,e.observed_at,e.expires_at,e.evidence_reference,e.evidence_detail,e.created_at
  from public.it_auth_security_evidence e
  order by e.control_key,e.observed_at desc,e.evidence_id desc
)
select
  c.control_key,
  c.control_title,
  c.secure_state_hint,
  l.evidence_id,
  l.evidence_source,
  l.observed_state,
  l.verification_status,
  coalesce(l.is_authoritative,false) as is_authoritative,
  l.observed_at,
  l.expires_at,
  l.evidence_reference,
  l.evidence_detail,
  case
    when l.evidence_id is null then 'pending_external_verification'
    when l.expires_at is not null and l.expires_at <= now() then 'stale_external_evidence'
    when l.observed_at < now()-interval '30 days' then 'stale_external_evidence'
    when not l.is_authoritative then 'pending_external_verification'
    when l.verification_status='verified_secure' and l.observed_state in ('enabled','configured') then 'verified_secure'
    when l.verification_status='verified_followup' or l.observed_state in ('disabled','not_configured') then 'verified_followup'
    else 'pending_external_verification'
  end::text as current_status,
  case
    when l.evidence_id is null then 'No current authoritative external evidence has been recorded.'
    when l.expires_at is not null and l.expires_at <= now() then 'Recorded external evidence has expired and must be re-verified.'
    when l.observed_at < now()-interval '30 days' then 'Recorded external evidence is older than 30 days and must be re-verified.'
    when not l.is_authoritative then 'Advisor/informational evidence cannot prove the external Auth setting.'
    when l.verification_status='verified_secure' and l.observed_state in ('enabled','configured') then 'Recent authoritative external evidence verifies the control as secure.'
    when l.verification_status='verified_followup' or l.observed_state in ('disabled','not_configured') then 'Recent authoritative evidence confirms that follow-up is still required.'
    else 'External Auth configuration still requires authoritative verification.'
  end::text as status_message,
  now() as checked_at
from controls c
left join latest l on l.control_key=c.control_key;

revoke all on table public.v_it_auth_security_evidence_current from public,anon,authenticated;
grant select on table public.v_it_auth_security_evidence_current to service_role;

create or replace view public.v_it_auth_security_evidence_status
with (security_invoker=true)
as
select
  count(*)::int as control_count,
  count(*) filter(where current_status='verified_secure')::int as verified_secure_count,
  count(*) filter(where current_status='verified_followup')::int as verified_followup_count,
  count(*) filter(where current_status='pending_external_verification')::int as pending_external_verification_count,
  count(*) filter(where current_status='stale_external_evidence')::int as stale_external_evidence_count,
  case when count(*) filter(where current_status<>'verified_secure')=0 then 'green' else 'amber' end::text as auth_security_status,
  'Auth-security GREEN requires recent authoritative external evidence for both controls. Advisor rows or absence of warnings never prove a dashboard setting.'::text as status_message,
  now() as checked_at
from public.v_it_auth_security_evidence_current;

revoke all on table public.v_it_auth_security_evidence_status from public,anon,authenticated;
grant select on table public.v_it_auth_security_evidence_status to service_role;

create or replace view public.v_it_current_admin_todo
with (security_invoker=true)
as
select
  ('rail:'||r.rail_key)::text as todo_key,
  r.rail_area::text as todo_area,
  r.rail_title::text as todo_title,
  r.technical_readiness_status::text as todo_status,
  r.current_action::text as current_action,
  r.evidence_requirement::text as evidence_requirement,
  r.requires_human,
  r.requires_external,
  r.resolution_class::text as source_kind,
  null::int as source_schema_version,
  r.sort_order::int as sort_order,
  r.checked_at
from public.v_it_open_rail_acceptance_readiness r
where r.rail_status<>'complete'
union all
select
  ('security:'||s.object_name)::text,
  'security'::text,
  case s.object_name
    when 'leaked_password_protection' then 'Verify leaked-password protection in Supabase Auth'
    when 'mfa_options' then 'Verify MFA options in Supabase Auth'
    when 'pg_net' then 'Review pg_net runtime placement constraint'
    else 'Review current security follow-up: '||s.object_name
  end::text,
  case
    when a.current_status='verified_followup' then 'followup_required'
    when a.current_status='stale_external_evidence' then 'stale_evidence'
    else 'pending'
  end::text,
  case s.object_name
    when 'leaked_password_protection' then 'Verify the current Supabase Auth leaked-password protection setting using the external Auth control plane. Record recent authoritative evidence; do not infer the setting from advisor silence.'
    when 'mfa_options' then 'Verify the current Supabase Auth MFA configuration using the external Auth control plane. Record recent authoritative evidence; do not infer the setting from advisor silence.'
    when 'pg_net' then 'Review current pg_net runtime dependency status; do not relocate unless the accepted runtime constraint has changed.'
    else 'Verify this security follow-up against its live authority before remediation.'
  end::text,
  case when s.object_kind='auth_setting'
    then 'Recent authoritative Supabase Dashboard/Management API evidence is required. Advisor rows and missing warnings are not sufficient proof.'
    else 'Current external/catalog evidence is required; historical advisor rows are not sufficient proof.' end::text,
  false,
  (s.reconciliation_state='external_verification')::boolean,
  'security_followup'::text,
  198::int,
  500 + row_number() over(order by s.object_name)::int,
  coalesce(a.checked_at,s.checked_at)
from public.v_it_security_advisor_truth s
left join public.v_it_auth_security_evidence_current a on a.control_key=s.object_name
where s.reconciliation_state in ('confirmed_followup','external_verification')
  and (
    s.object_name<>'pg_net'
    or not exists(select 1 from public.v_it_pg_net_runtime_dependency_status p where p.status='accepted')
  )
  and (
    s.object_kind<>'auth_setting'
    or coalesce(a.current_status,'pending_external_verification')<>'verified_secure'
  )
union all
select
  'repository:main_protection'::text,
  'release'::text,
  'Protect main branch repository enforcement'::text,
  ra.repository_enforcement_status::text,
  'Enable and verify main branch protection/ruleset enforcement, then record current branch-policy evidence. This remains separate from application release authority.'::text,
  'GitHub must report current main protection/ruleset enforcement; do not infer protection from a green application workflow.'::text,
  false,
  true,
  'repository_followup'::text,
  ra.release_schema_version::int,
  900::int,
  ra.checked_at
from public.v_it_release_authority_status ra
where lower(coalesce(ra.repository_enforcement_status,''))<>'green';

revoke all on table public.v_it_current_admin_todo from public,anon,authenticated;
grant select on table public.v_it_current_admin_todo to service_role;

create or replace view public.v_it_current_admin_todo_status
with (security_invoker=true)
as
select
  count(*)::int as current_todo_count,
  count(*) filter(where todo_key like 'rail:%')::int as business_acceptance_count,
  count(*) filter(where source_kind='security_followup')::int as security_followup_count,
  count(*) filter(where source_kind='repository_followup')::int as repository_followup_count,
  count(*) filter(where requires_human)::int as human_required_count,
  count(*) filter(where requires_external)::int as external_required_count,
  case when count(*)=0 then 'green' else 'amber' end::text as todo_status,
  'Only current unresolved actions appear here. Auth-security items close only from recent authoritative external evidence; accepted runtime constraints and historical checklists stay out of active work.'::text as status_message,
  now() as checked_at
from public.v_it_current_admin_todo;

revoke all on table public.v_it_current_admin_todo_status from public,anon,authenticated;
grant select on table public.v_it_current_admin_todo_status to service_role;

create or replace function public.ywi_auth_security_evidence_assertions()
returns table(assertion_key text,assertion_status text,assertion_detail text)
language sql
security definer
set search_path=public,pg_temp
as $$
  select 'auth_controls_catalogued',
    case when (select count(*) from public.v_it_auth_security_evidence_current)=2 then 'passed' else 'failed' end,
    'Exactly leaked-password protection and MFA options are represented in current Auth-security evidence authority.'
  union all select 'advisor_not_authoritative_for_auth_settings',
    case when not exists(
      select 1 from public.it_auth_security_evidence
      where evidence_source='supabase_advisor' and is_authoritative=true
    ) then 'passed' else 'failed' end,
    'Supabase advisor evidence cannot be recorded as authoritative proof of an Auth dashboard setting.'
  union all select 'verified_secure_requires_authoritative_external_evidence',
    case when not exists(
      select 1 from public.it_auth_security_evidence
      where verification_status='verified_secure'
        and (is_authoritative=false or evidence_source='supabase_advisor' or observed_state not in ('enabled','configured'))
    ) then 'passed' else 'failed' end,
    'Verified-secure evidence is constrained to authoritative external evidence with a secure observed state.'
  union all select 'current_auth_followups_truthful',
    case when (
      select count(*) from public.v_it_current_admin_todo
      where todo_key in ('security:leaked_password_protection','security:mfa_options')
    ) = (
      select count(*) from public.v_it_auth_security_evidence_current where current_status<>'verified_secure'
    ) then 'passed' else 'failed' end,
    'Current Admin To-Do agrees with current Auth-security evidence truth.'
  union all select 'auth_evidence_authority_service_private',
    case when not has_table_privilege('anon','public.it_auth_security_evidence','select')
      and not has_table_privilege('authenticated','public.it_auth_security_evidence','select')
      and has_table_privilege('service_role','public.it_auth_security_evidence','select')
      and not has_table_privilege('anon','public.v_it_auth_security_evidence_current','select')
      and not has_table_privilege('authenticated','public.v_it_auth_security_evidence_current','select')
      and has_table_privilege('service_role','public.v_it_auth_security_evidence_current','select')
    then 'passed' else 'failed' end,
    'Auth-security evidence authority is service-role-only.'
  union all select 'open_business_acceptance_unchanged',
    case when (select count(*) from public.v_it_open_rail_acceptance_readiness where rail_status<>'complete')=11 then 'passed' else 'failed' end,
    'All 11 human/provider/accounting/content/staging acceptance rails remain open.'
  union all select 'finance_provider_execution_off',
    case when not exists(
      select 1 from public.finance_job_completion_posting_execution_controls
      where execution_enabled=true or provider_mutation_enabled=true
    ) then 'passed' else 'failed' end,
    'Finance posting execution and payment-provider mutation remain OFF.';
$$;

revoke all on function public.ywi_auth_security_evidence_assertions() from public,anon,authenticated;
grant execute on function public.ywi_auth_security_evidence_assertions() to service_role;

insert into public.it_readiness_check_registry(check_key,check_group,check_title,severity_if_failed,action_hint,route_hint,sort_order,is_enabled)
values(
  'auth_security_evidence_authority','Security','Supabase Auth security evidence authority','critical',
  'Verify leaked-password protection and MFA with recent authoritative external evidence. Advisor rows or warning absence are not sufficient proof.',
  'Admin > Account Security / I.T. Readiness',35,true
)
on conflict(check_key) do update set
  check_group=excluded.check_group,check_title=excluded.check_title,severity_if_failed=excluded.severity_if_failed,
  action_hint=excluded.action_hint,route_hint=excluded.route_hint,sort_order=excluded.sort_order,is_enabled=excluded.is_enabled,updated_at=now();

insert into public.admin_scorecard_progress_rails(
  rail_key,rail_area,rail_title,rail_status,progress_percent,current_value,target_value,next_action_hint,owner_hint,sort_order,metadata
) values(
  'schema198_auth_security_evidence_authority','admin','Auth security evidence authority','active',80,8,10,
  'Verify Schema 198 assertions, service-private evidence authority, current Admin To-Do truth, source/browser gates, exact accepted tree, release evidence, and cleanup. Do not auto-close Auth settings without current external proof.',
  'Admin / I.T. / Security',118,jsonb_build_object(
    'schema',198,'auth_setting_mutation',false,'advisor_auto_verification',false,'business_rail_auto_close',false,
    'finance_mutation',false,'payment_provider_mutation',false,'production_promotion',false
  )
)
on conflict(rail_key) do update set
  rail_area=excluded.rail_area,rail_title=excluded.rail_title,rail_status=excluded.rail_status,
  progress_percent=excluded.progress_percent,current_value=excluded.current_value,target_value=excluded.target_value,
  next_action_hint=excluded.next_action_hint,owner_hint=excluded.owner_hint,sort_order=excluded.sort_order,
  metadata=excluded.metadata,updated_at=now();

insert into public.it_scorecard_rail_resolution_contracts(
  rail_key,resolution_class,requires_human,requires_external,auto_close_allowed,resolution_note,introduced_by_schema
) values(
  'schema198_auth_security_evidence_authority','build_acceptance',false,false,false,
  'Close the Build 198 technical rail only after schema/source/browser/release proof is green. The separate leaked-password and MFA follow-ups remain external evidence requirements and are not auto-closed by this build.',198
)
on conflict(rail_key) do update set
  resolution_class=excluded.resolution_class,requires_human=excluded.requires_human,requires_external=excluded.requires_external,
  auto_close_allowed=excluded.auto_close_allowed,resolution_note=excluded.resolution_note,
  introduced_by_schema=excluded.introduced_by_schema,updated_at=now();

insert into public.app_schema_versions(schema_version,schema_name,description,status,applied_by,notes,migration_key,release_label)
values(
  198,
  '198_auth_security_evidence_authority',
  'Adds service-private, freshness-aware external evidence authority for Supabase Auth leaked-password protection and MFA without changing Auth settings.',
  'applied','schema198',
  'No Auth mutation, business rail closure, Finance/provider mutation, or Production promotion.',
  '198_auth_security_evidence_authority.sql','schema198'
)
on conflict(schema_version) do update set
  schema_name=excluded.schema_name,description=excluded.description,status=excluded.status,
  applied_at=now(),applied_by=excluded.applied_by,notes=excluded.notes,migration_key=excluded.migration_key,release_label=excluded.release_label;

create or replace view public.v_schema_drift_status with (security_invoker=true) as
select 198::int as expected_schema_version,
       coalesce(max(schema_version) filter(where status='applied'),0)::int as latest_applied_schema_version,
       case when coalesce(max(schema_version) filter(where status='applied'),0)>=198 then 'current' else 'drift' end::text as drift_status,
       case when coalesce(max(schema_version) filter(where status='applied'),0)>=198
         then 'Live database is at or ahead of the repo schema marker.'
         else 'Live database is behind the repo schema marker.' end::text as message,
       now() as checked_at
from public.app_schema_versions;

revoke all on table public.v_schema_drift_status from public,anon,authenticated;
grant select on table public.v_schema_drift_status to service_role;

commit;
