-- 2026-03-24_recovery_inventory_moderation_and_checkout.sql
create extension if not exists pgcrypto;
alter table public.bookings add column if not exists payment_provider text null, add column if not exists paypal_order_id text null, add column if not exists paypal_capture_id text null;
alter table public.job_updates add column if not exists parent_update_id uuid null references public.job_updates(id) on delete cascade, add column if not exists thread_status text not null default 'visible', add column if not exists moderated_at timestamptz null, add column if not exists moderated_by_name text null, add column if not exists moderation_reason text null;
alter table public.job_media add column if not exists thread_status text not null default 'visible', add column if not exists moderated_at timestamptz null, add column if not exists moderated_by_name text null, add column if not exists moderation_reason text null;
create table if not exists public.recovery_message_templates (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), template_key text not null unique, channel text not null check (channel in ('email','sms')), provider text not null default 'manual', is_active boolean not null default true, subject_template text null, body_template text not null, variables jsonb not null default '[]'::jsonb, rules jsonb not null default '{}'::jsonb, notes text null);
create table if not exists public.catalog_inventory_items (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), item_key text not null unique, item_type text not null check (item_type in ('tool','consumable')), name text not null, category text null, description text null, image_url text null, amazon_url text null, is_public boolean not null default true, is_active boolean not null default true, qty_on_hand numeric(12,2) not null default 0, reorder_point numeric(12,2) not null default 0, reorder_qty numeric(12,2) not null default 0, unit_label text null, cost_cents integer null, preferred_vendor text null, vendor_sku text null, rating_value numeric(3,2) null, rating_count integer not null default 0, notes text null);
create table if not exists public.catalog_low_stock_alerts (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), item_id uuid not null references public.catalog_inventory_items(id) on delete cascade, item_key text null, qty_snapshot numeric(12,2) null, reorder_point_snapshot numeric(12,2) null, is_resolved boolean not null default false, resolved_at timestamptz null, resolved_by_name text null, resolution_notes text null);
create table if not exists public.catalog_purchase_orders (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), item_id uuid null references public.catalog_inventory_items(id) on delete set null, item_key text null, item_name text null, vendor_name text null, qty_ordered numeric(12,2) not null default 0, unit_cost_cents integer null, status text not null default 'draft', reminder_at timestamptz null, ordered_at timestamptz null, received_at timestamptz null, purchase_url text null, note text null);
create table if not exists public.app_management_settings (key text primary key, value jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now());
insert into public.app_management_settings (key, value, updated_at) values ('payment_methods', '{"stripe": true, "gift_only_confirm": true}'::jsonb, now()), ('recovery_provider_rules', '{"email":{"enabled":true,"allowed_providers":["manual","resend"]},"sms":{"enabled":false,"allowed_providers":["manual"]}}'::jsonb, now()) on conflict (key) do update set value = excluded.value, updated_at = now();
